export default {
  nodes: [
    { id: "Front end", group: 7 },
    // {id: "Data", group: 3},
    { id: "HTML5", group: 2 },
    { id: "JSX", group: 2 },
    { id: "Gatsby", group: 1 },
    { id: "CSS3", group: 3 },
    { id: "SASS", group: 3 },
    { id: "React Native", group: 6 },
    { id: "React", group: 6 },
    { id: "Redux", group: 4 },
    { id: "MobX", group: 4 },
    { id: "Expo", group: 1 },
  ],
  links: [
    { source: "Front end", target: "React", value: 3 },
    { source: "Front end", target: "HTML5", value: 3 },
    { source: "Front end", target: "CSS3", value: 3 },
    { source: "Front end", target: "SASS", value: 3 },
    { source: "Front end", target: "React Native", value: 3 },
    { source: "Front end", target: "React", value: 3 },
    { source: "React", target: "Redux", value: 1 },
    { source: "React", target: "MobX", value: 1 },
    { source: "React Native", target: "Redux", value: 1 },
    { source: "React", target: "JSX", value: 1 },
    { source: "React", target: "Gatsby", value: 1 },
    { source: "CSS3", target: "SASS", value: 1 },
    { source: "CSS3", target: "React", value: 1 },
    { source: "React", target: "SASS", value: 1 },
    { source: "HTML5", target: "JSX", value: 1 },
    { source: "Expo", target: "React Native", value: 1 },
    { source: "MobX", target: "React Native", value: 1 },
  ],
}
